### ISSUE TITLE
crash if create bundle

### ISSUE THREAD

**Issue by nerzh** [mdorofeev/ton-client-kotlin#21]
I have this issue when I try to create release .aap(NOT .APK) build in android studio **File 'root/lib/arm64-v8a/libcrypto.so.1.1' uses reserved file or directory name 'lib'.**

Please, fix it, because **without it, it is impossible to publish the application in Google play store**. 
I am really looking forward to

Best Regards,
Me

**Comment by mdorofeev** [comment]
Moved android binaries to separate aar. It can be found in android example project.
