### ISSUE TITLE
properties mismatch

### ISSUE THREAD

**Issue by nerzh** [mdorofeev/ton-client-kotlin#26]
the mode property instead of other properties, e.g. 

**skip_transaction_check
boc_cache
return_updated_account**

https://github.com/mdorofeev/ton-client-kotlin/blob/master/src/main/kotlin/ee/nx01/tonclient/tvm/Types.kt#L63

https://github.com/tonlabs/TON-SDK/blob/master/ton_client/src/tvm/run_message.rs#L119

**Comment by mdorofeev** [comment]
added missed properties in version 0.0.42
