### ISSUE TITLE
Hardcoded set of contracts

### ISSUE THREAD

**Issue by vp-mazekine** [mdorofeev/ton-client-kotlin#8]
The current implementation of the library contains the hard-coded path to possible ABIs:

![image](https://user-images.githubusercontent.com/59574999/113605266-1727d000-964f-11eb-8655-703df6794f23.png)

Please make the possibility to specify an arbitrary path to the ABI scheme or TVC file.

E.g., I was unable to use this schema to communicate with the contest contract:
https://github.com/tonlabs/ton-labs-contracts/blob/master/solidity/contest/FreeTonContest.abi.json

**Comment by mdorofeev** [comment]
PR merged, release 0.0.24 done
